config/routes.rb
Rails.application.routes.draw do
  
  root 'access#menu'

  get 'admin', :to => 'access#menu'
  get 'access/menu'
  get 'access/login'
  post 'access/attempt_login'
  get 'access/logout'

  get 'admin_users/reset', :to => 'admin_users#reset'

  resources :admin_users do
     member do
      get :delete
     end
  end

  resources :questions do
     member do
      get :delete
     end
  end

  resources :exams do
     member do
      get :delete
     end
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord

	has_secure_password

	scope :sorted, lambda {order('superuser DESC, year DESC,section, email, roll_number, first_name, last_name, username')}
	
	def name
		"#{first_name} #{last_name}"
	end

	validates_presence_of :username, :password, :year, :first_name, :last_name, :section, :roll_number, :email, :user_mobile, :father, :father_occupation, :father_mobile, :mother, :mother_occupation, :mother_mobile, :interests, :goals, :skills, :strengths, :weaknesses

	validates_uniqueness_of :username

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord

	scope :sorted, lambda {order('id DESC')}

end

app/controllers/access_controller.rb
class AccessController < ApplicationController

	before_action :confirm_logged_in, :except => [:login, :attempt_login, :logout]

	def menu
		@username = session[:username]
		redirect_to(admin_users_path)
	end

	def login
	end

	def attempt_login
		if params[:username].present? && params[:password].present?
			found_user = AdminUser.where(:username => params[:username]).first
			if found_user
				authorized_user = found_user.authenticate(params[:password])
			end
		end

		if authorized_user
			session[:user_id] = authorized_user.id
			session[:username] = authorized_user.username
			if found_user.superuser?
				redirect_to(admin_path)
			else
				if (found_user.score == -1)
					redirect_to(edit_exam_path(session[:user_id]))
				else
					redirect_to(exams_path)
				end
			end
		else
			flash.now[:danger] = "Invalid username or password."
			render('login')
		end
	end

	def logout
		session[:user_id] = nil
		session[:username] = nil
		flash[:success] = 'You are logged out.'
		redirect_to(access_login_path)
	end
	
end

app/controllers/admin_users_controller.rb
class AdminUsersController < ApplicationController

	before_action :confirm_logged_in, :except => [:new, :create]
	before_action :is_superuser
	# , :except => [:new, :create]

	def index
		@admin_users = AdminUser.sorted
	end

	def show
		@admin_user = AdminUser.find(params[:id])
	end

	def new
		@admin_user = AdminUser.new
	end

	def create
		@admin_user = AdminUser.new(admin_user_params)
		@admin_user.user_mobile = "NA"
		@admin_user.father = "NA"
		@admin_user.father_occupation = "NA"
		@admin_user.father_mobile = "NA"
		@admin_user.mother = "NA"
		@admin_user.mother_occupation = "NA"
		@admin_user.mother_mobile = "NA"
		@admin_user.interests = "NA"
		@admin_user.goals = "NA"
		@admin_user.skills = "NA"
		@admin_user.strengths = "NA"
		@admin_user.weaknesses = "NA"
		if @admin_user.save
			flash[:success] = 'User created successfully.'
			redirect_to(admin_users_path)
		else
			render('new')
		end
	end

	def edit
		@admin_user = AdminUser.find(params[:id])
	end

	def update
		@admin_user = AdminUser.find(params[:id])
		if @admin_user.update_attributes(admin_user_params)
			flash[:success] = 'User updated successfully.'
			redirect_to(admin_users_path)
		else
			render('edit')
		end
	end

	def delete
		@admin_user = AdminUser.find(params[:id])
		if @admin_user.superuser
			flash[:success] = 'Site Administrator cannot be deleted.'
			redirect_to(admin_users_path)
		end
	end

	def destroy
		@admin_user = AdminUser.find(params[:id])
		@admin_user.destroy
		flash[:success] = 'User destroyed successfully.'
		redirect_to(admin_users_path)
	end

	def reset
		users = AdminUser.all
		users.each do |user|
			user.update_attribute(:score, -1)
			user.update_attribute(:answered, "")
		end
		redirect_to(admin_users_path)
	end

	private

	def admin_user_params
		params.require(:admin_user).permit(
			:year,
			:first_name,
			:last_name,
			:section,
			:roll_number,
			:email,
			:user_mobile,
			:father,
			:father_occupation,
			:father_mobile,
			:mother,
			:mother_occupation,
			:mother_mobile,
			:interests,
			:goals,
			:skills,
			:strengths,
			:weaknesses,
			:username,
			:password,
			:answered,
			:score
			)
	end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

private
	
	def confirm_logged_in
		unless session[:user_id]
			redirect_to(access_login_path)
		end
		if session[:user_id]
			user = AdminUser.find(session[:user_id])
			if !user.superuser
				if (user.score != -1)
					if (Time.now-user.created_at > 1200)
						redirect_to('/access/logout')
					end
				end
			end
		end
	end

	def is_superuser
		user = AdminUser.find(session[:user_id])
		unless user.superuser?
			redirect_to(exams_path)
		end
	end
  
end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController

  before_action :confirm_logged_in

  def index
    user = AdminUser.find(session[:user_id])
    questions = Question.ids.map(&:to_s)
    answers = user.answered.split
    difference = questions - answers
    if difference.size != 0
      @question = Question.find(difference[rand(0...(difference.size))])
      new_answered = user.answered + @question.id.to_s + " "
      if (user.score == -1)
        user.update_attribute(:created_at, Time.now)
        user.update_attribute(:score, 0)
      end
      user.update_attribute(:answered, new_answered)
    else
      redirect_to('/access/logout')
    end
  end

  def show
    user = AdminUser.find(session[:user_id])
    if (question = Question.find(params[:question_id]))
      if params[:answer] == question.answer
        score = user.score + 1
        user.update_attribute(:score, score)
      end
    end
    redirect_to(exams_path)
  end

  def edit
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  before_action :confirm_logged_in
  before_action :is_superuser

  # READ ACTIONS
  def index
    @questions = Question.all.sorted
  end

  def show
    @question = Question.find(params[:id])
  end

  # CREATE ACTIONS
  def new
    @question = Question.new
  end

  def create
    @question = Question.new(:description=> params[:question][:description], :answer => params[:question][:answer], :one => params[:question][:one], :two => params[:question][:two], :three => params[:question][:three])
    if @question.save
      flash[:success] = "Question created successfully."
      redirect_to(questions_path)
    else
      flash[:danger].now = "Question form error."
      render 'new'
    end
  end

  # UPDATE ACTIONS
  def edit
    @question = Question.find(params[:id])
  end

  def update
    @question = Question.find(params[:id])
    if @question.update_attributes(question_params)
      redirect_to (questions_path)
    else
      render 'edit'
    end
  end

  # DELETE ACTIONS
  def delete
    @question = Question.find(params[:id])
  end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy
    flash[:success] = "Question '#{@question.id}' deleted successfully."
    redirect_to(questions_path)
  end

  private

  def question_params
    params.require(:question).permit(:description, :answer, :one, :two, :three)
  end

end

app/helpers/access_helper.rb
module AccessHelper
end

app/helpers/admin_users_helper.rb
module AdminUsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/views/access/login.html.erb
<div class="center jumbotron">
  <h1>Welcome!</h1>
  <%= form_tag(access_attempt_login_path, :method => :post, :class => 'form-horizontal', :role => 'form' ) do %>
      <div class="form-group">
        <%= label_tag(:username, nil, class: 'col-sm-2 control-label') %>
        <div class="col-sm-8">
          <%= text_field_tag(:username, params[:username], :class => 'form-control', :placeholder => 'Enter Username') %>
        </div>
      </div>
      <div class="form-group">
        <br>
        <%= label_tag(:password, nil, class: 'col-sm-2 control-label') %>
        <div class="col-sm-8">
          <%= password_field_tag(:password, nil, :class => 'form-control', :placeholder => 'Enter Password') %>
        </div>
      </div>
      <br/>
      <div class="form-group">
        <div class="col-sm-5">
          <%= submit_tag("Login", :class => 'btn btn-danger btn-lg')  %>
          <%#= link_to("Register", new_admin_user_path, :class => 'btn btn-primary btn-lg') %>
        </div>
      </div>
  <% end %>
</div>

app/views/admin_users/_form.html.erb
<div class="form-group">
  <%= f.label :year, class: 'col-sm-2 control-label' %>
  <div class="col-sm-8">
    <%= f.text_field :year, class: 'form-control', placeholder: 'The year in which you will pass out', autofocus: true %>
  </div>
</div>

<div class="form-group">
  <%= f.label :first_name, class: 'col-sm-2 control-label' %>
  <div class="col-sm-8">
    <%= f.text_field :first_name, class: 'form-control', placeholder: 'First name of user', autofocus: true %>
  </div>
</div>
<div class="form-group">
  <%= f.label :last_name, class: 'col-sm-2 control-label' %>
  <div class="col-sm-8">
    <%= f.text_field :last_name, class: 'form-control', placeholder: 'Last name of user', autofocus: true %>
  </div>
</div>
<div class="form-group">
  <%= f.label :section, class: 'col-sm-2 control-label' %>
  <div class="col-sm-8">
    <%= f.text_field :section, class: 'form-control', placeholder: 'Name of your Section', autofocus: true %>
  </div>
</div>
<div class="form-group">
  <%= f.label :roll_number, class: 'col-sm-2 control-label' %>
  <div class="col-sm-8">
    <%= f.text_field :roll_number, class: 'form-control', placeholder: 'Your class roll number', autofocus: true %>
  </div>
</div>
<div class="form-group">
  <%= label_tag 'email', 'Branch', class: 'col-sm-2 control-label' %>
  <div class="col-sm-8">
    <%= f.text_field :email, class: 'form-control', placeholder: 'Your branch', autofocus: true %>
  </div>
</div>
<div class="form-group">
  <%= f.label :username, class: 'col-sm-2 control-label' %>
  <div class="col-sm-8">
    <%= f.text_field :username, class: 'form-control', placeholder: 'Your unique Username (this will be required during login)', autofocus: true %>
  </div>
</div>
<div class="form-group">
  <%= f.label :password, class: 'col-sm-2 control-label' %>
  <div class="col-sm-8">
    <%= f.text_field :password, class: 'form-control', placeholder: 'Your Password (this will be required during login)', autofocus: true %>
  </div>
</div>

app/views/admin_users/delete.html.erb
<% @page_title = "Delete User"%>
<%= form_for(@admin_user,:method => 'delete') do |f| %>
    <div class="center page-header">
      <h2>Delete [<%= f.object.username %>]?</h2>
    </div>
    <div class="center form-group">
      <p>Are you sure you want to delete this user?</p>
      <div class="col-sm-12">
        <%= f.submit "Delete User",class: 'btn btn-danger btn-lg' %>
      </div>
    </div>
<% end %>

app/views/admin_users/edit.html.erb
<% @page_title = "Update User"%>
<div class="center page-header">
  <h2>Edit User</h2>
</div>
<%= form_for @admin_user, html: { class: 'form-horizontal', role: 'form' } do |f| %>
		<%= render(:partial => 'form', :locals => {:f => f}) %>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit "Update User",class: 'btn btn-primary btn-lg' %>
      </div>
    </div>
<% end %>

app/views/admin_users/index.html.erb
<% @page_title = "Manage Users" %>
<div class="center page-header">
  <h2>Manage Users</h2>
  <%= pluralize(@admin_users.size, 'user') %> found
  <div class="center">
    <%= link_to("Register User", new_admin_user_path, :class => 'btn btn-primary') %>
    <%= link_to("Reset Everything", admin_users_reset_path, :class => 'btn btn-danger') %>
  </div>
</div>
<div>
  <table class="table table-bordered table-striped table-hover table-condensed">
    <tr>
      <th>Year</th>
      <th>Branch</th>
      <th>Section</th>
      <th>Roll number</th>
      <th>Name</th>
      <th>Score</th>
      <th>Username</th>
      <th>Actions</th>
    </tr>
    <% @admin_users.each do |admin_user| %>
        <tr>
          <td><%= admin_user.year %></td>
          <td><%= admin_user.email %></td>
          <td><%= admin_user.section %></td>
          <td><%= admin_user.roll_number %></td>
          <td><%= admin_user.name %></td>
          <td><%= admin_user.score %></td>
          <td><%= admin_user.username %></td>
          <td>
            <%= link_to('Details', admin_user_path(admin_user), :class => 'btn btn-primary btn-sm') %>
            <%= link_to('Edit', edit_admin_user_path(admin_user), :class => 'btn btn-info btn-sm') %>
            <%= link_to('Delete', delete_admin_user_path(admin_user), :class => 'btn btn-danger btn-sm') %>
          </td>
        </tr>
    <% end %>
  </table>
</div>

app/views/admin_users/new.html.erb
<% @page_title = "Register"%>
<div class="center page-header">
  <h2>User Registeration Form</h2>
  <h5>Please take your time to fill all fields correctly.</h5>
  <h5>Incomplete forms will be rejected by the system.</h5>
</div>
<%= form_for @admin_user, html: { class: 'form-horizontal', role: 'form' } do |f| %>
    <%= render(:partial => 'form', :locals => {:f => f}) %>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit "Register",class: 'btn btn-primary btn-lg' %>
      </div>
    </div>
<% end %>

app/views/admin_users/show.html.erb
<% @page_title = @admin_user.name%>
<div class="center page-header">
  <h2>Details of [<%= @admin_user.username %>]</h2>
</div>
<div class="well col-xs-8 col-xs-offset-2">
	<table class="table table-bordered table-striped table-hover table-condensed">
		<tr>
			<td class="active data">Name</td>
			<td class="info text-center object-code"> <%= @admin_user.name %> </td>
		</tr>
		<tr>
			<td class="active data">Section</td>
			<td class="info text-center object-code"> <%= @admin_user.section %> </td>
		</tr>
		<tr>
			<td class="active data">Roll number</td>
			<td class="info text-center object-code"> <%= @admin_user.roll_number %> </td>
		</tr>
		<tr>
			<td class="active data">Year</td>
			<td class="info text-center object-code"> <%= @admin_user.year %> </td>
		</tr>
		<tr>
			<td class="active data">Email</td>
			<td class="info text-center object-code"> <%= mail_to(@admin_user.email) %> </td>
		</tr>
		<tr>
			<td class="active data">Contact number</td>
			<td class="info text-center object-code"> <%= @admin_user.user_mobile %> </td>
		</tr>
		<tr>
			<td class="active data">Father's Name</td>
			<td class="info text-center object-code"> <%= @admin_user.father %> </td>
		</tr>
		<tr>
			<td class="active data">Father's Occupation</td>
			<td class="info text-center object-code"> <%= @admin_user.father_occupation %> </td>
		</tr>
		<tr>
			<td class="active data">Father's Contact number</td>
			<td class="info text-center object-code"> <%= @admin_user.father_mobile %> </td>
		</tr>
		<tr>
			<td class="active data">Mother's Name</td>
			<td class="info text-center object-code"> <%= @admin_user.mother %> </td>
		</tr>
		<tr>
			<td class="active data">Mother's Occupation</td>
			<td class="info text-center object-code"> <%= @admin_user.mother_occupation %> </td>
		</tr>
		<tr>
			<td class="active data">Mother's Contact number</td>
			<td class="info text-center object-code"> <%= @admin_user.mother_mobile %> </td>
		</tr>
		<tr>
			<td class="active data">Interests</td>
			<td class="info text-center object-code"> <%= @admin_user.interests %> </td>
		</tr>
		<tr>
			<td class="active data">Goals</td>
			<td class="info text-center object-code"> <%= @admin_user.goals %> </td>
		</tr>
		<tr>
			<td class="active data">Skills</td>
			<td class="info text-center object-code"> <%= @admin_user.skills %> </td>
		</tr>
		<tr>
			<td class="active data">Strengths</td>
			<td class="info text-center object-code"> <%= @admin_user.strengths %> </td>
		</tr>
		<tr>
			<td class="active data">Weaknesses</td>
			<td class="info text-center object-code"> <%= @admin_user.weaknesses %> </td>
		</tr>
		<tr>
			<td class="active data">Username</td>
			<td class="info text-center object-code"> <%= @admin_user.username %> </td>
		</tr>
		<tr>
			<td class="active data">Score</td>
			<td class="info text-center object-code"> <%= @admin_user.score %> </td>
		</tr>
	</table>
</div>

app/views/exams/delete.html.erb
<h1>Exams#delete</h1>
<p>Find me in app/views/exams/delete.html.erb</p>

app/views/exams/edit.html.erb
<div class="well">
	<p>Please read the instructions carefully before starting test:</p>
	<p><ul><li><strong>Once you click the 'Start test' button, you will have 20 minutes to answer the questions.</strong></li></p>
	<p><li><strong>Each question will have multiple choices.</strong></li></p>
	<p><li><strong>After the time for test expires or after you have attempted all questions, you will be logged out of the system.</strong></li></p>
	<p><li><strong>Please do not refresh the page while taking test, if you do refresh, you will not be rewarded any marks for the question. </strong></li></p>
	<p><li><strong>The test results will be announced offline by the System Administrator.</strong></li></ul></p>
	<%= link_to("Start test", exams_path, :class => 'btn btn-primary btn-lg') %>
</div>

app/views/exams/index.html.erb
<% @page_title = "Test Centre" %>
<div class="center page-header">
	<h2><%= simple_format(@question.description) %></h2>
</div>
<div class="center well col-xs-6 col-xs-offset-3">
	<%= form_tag '/exams/show', :method => 'get', class: 'form-horizontal', role: 'form' do %>
		<%= hidden_field_tag :question_id, @question.id %>
		<% a = [] %>
		<%  a[0] = @question.answer %>
		<%  a[1] = @question.one %>
		<%  a[2] = @question.two %>
		<%  a[3] = @question.three %>
		<%  for i in 0...4 do %>
			<% j = rand(0...4) %>
			<% a[i],a[j] = a[j],a[i] %>
		<%  end %>
		<%= radio_button_tag :answer, a[0], autofocus: true %><%= simple_format(a[0]) %><br>
		<%= radio_button_tag :answer, a[1] %><%= simple_format(a[1]) %><br>
		<%= radio_button_tag :answer, a[2] %><%= simple_format(a[2]) %><br>
		<%= radio_button_tag :answer, a[3] %><%= simple_format(a[3]) %><br>
		<div id="margiretta">
			<%= submit_tag "Next", class: 'btn btn-primary btn-lg' %>
		</div>
	<% end %>
</div>

app/views/exams/new.html.erb
<h1>Exams#new</h1>
<p>Find me in app/views/exams/new.html.erb</p>

app/views/exams/show.html.erb
<h1>Exams#show</h1>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Copyright &copy; Rajat Pundir, Prateek Alakh
  </small>
</footer>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <% flash.each do |name, msg| %>
        <div class="alert alert-<%= name %> alert-dismissible" role="alert">
          <a href="#" class="close" data-dismiss="alert" aria-label="Close">&#215;</a>
          <%= msg %>
        </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Compilest", '#' , class: "navbar-brand", id: "logo" %>
    </div>
    <% if is_logged_in %>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <% if user.superuser? %>
              <ul class="nav navbar-nav">
                <li><%= link_to "Manage Users", admin_users_path %></li>
                <li><%= link_to "Manage Questions", questions_path %></li>
              </ul>
          <% end %>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to user.name, '' %></li>
            <li><%= link_to "Logout", access_logout_path %></li>
          </ul>
        </div>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title><%= @page_title || "Compilest" %> </title>
	<%= csrf_meta_tags %>

	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
	<% user = AdminUser.where(:username => session[:username]).first %>
	<% if user %>
	<%= render 'layouts/navigation', :is_logged_in => true, :user => user %>
	<% else %>
	<%= render 'layouts/navigation', :is_logged_in => false %>
	<% end %>
	<%= render 'layouts/messages' %>
	<div class="container">
		<%= yield %>
	</div>
	<%= render 'layouts/footer' %>
</body>
</html>

app/views/questions/_form.html.erb
<div class="form-group">
  <%= f.label :description, class: 'col-sm-2 control-label' %>
  <div class="col-sm-8">
    <%= f.text_area :description,  rows: '10', class: 'form-control', placeholder: 'Write question description', autofocus: true %>
  </div>
</div>
<div class="form-group">
  <%= f.label :answer, class: 'col-sm-2 control-label' %>
  <div class="col-sm-8">
    <%= f.text_area :answer,  rows: '10', class: 'form-control', placeholder: 'Write the answer for question', autofocus: true %>
  </div>
</div>
<div class="form-group">
  <%= f.label :one, class: 'col-sm-2 control-label' %>
  <div class="col-sm-8">
    <%= f.text_area :one,  rows: '10', class: 'form-control', placeholder: 'Write false choices', autofocus: true %>
  </div>
</div>
<div class="form-group">
  <%= f.label :two, class: 'col-sm-2 control-label' %>
  <div class="col-sm-8">
    <%= f.text_area :two,  rows: '10', class: 'form-control', placeholder: 'Write false choices', autofocus: true %>
  </div>
</div>
<div class="form-group">
  <%= f.label :three, class: 'col-sm-2 control-label' %>
  <div class="col-sm-8">
    <%= f.text_area :three,  rows: '10', class: 'form-control', placeholder: 'Write false choices', autofocus: true %>
  </div>
</div>

app/views/questions/delete.html.erb
<% @page_title = "Delete Question"%>
<%= form_for(@question,:method => 'delete') do |f| %>
<div class="center page-header">
  <h2><%= f.object.description %>?</h2>
</div>
    <div class="center form-group">
      <p>Are you sure you wish to permanently delete this?</p>
      <div class="col-sm-12">
        <%= f.submit "Delete Question",class: 'btn btn-danger btn-lg' %>
      </div>
    </div>
<% end %>

app/views/questions/edit.html.erb
<% @page_title = "Create Test"%>
<div class="center page-header">
  <h2>Edit Test</h2>
</div>
	<%= form_for(@question,:url=> question_path(@question),:method => 'patch', :html => {:class => 'form-horizontal', :role => 'form'}) do |f| %>
    <<%= render(:partial => 'form', :locals => {:f => f}) %>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit "OK",class: 'btn btn-primary btn-lg' %>
      </div>
    </div>
	<% end %>

app/views/questions/index.html.erb
<% @page_title = "Manage Questions" %>
<div class="center page-header">
  <h2>Manage Questions</h2>
  <%= link_to "Add new Question", new_question_path, :class => 'btn btn-primary' %>
</div>
<div class="col-xs-8 col-xs-offset-2 well well-lg">
  <table class="table table-bordered table-striped table-hover table-condensed">
    <% @questions.each do |question| %>
        <tr>
          <td>Question ID: <%= question.id %></td>
          <td>
            <div >
            <%= link_to("Show", question_path(question), :class => 'btn btn-info') %>
            <%= link_to("Edit", edit_question_path(question), :class => 'btn btn-info') %>
            <%= link_to("Delete", delete_question_path(question), :class => 'btn btn-danger') %>
            </div>
          </td>
        </tr>
    <% end %>
  </table>
</div>

app/views/questions/new.html.erb
<% @page_title = "Create Question" %>
<div class="center page-header">
  <h2>Create Question</h2>
</div>
	<%= form_for(@question, :url=> questions_path, :method => 'post', :html => {:class => 'form-horizontal', :role => 'form'} ) do |f| %>
    <%= render(:partial => 'form', :locals => {:f => f}) %>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit "Create Question", class: 'btn btn-primary btn-lg' %>
      </div>
    </div>
	<% end %>

app/views/questions/show.html.erb
<div class="center page-header">
  <h2><%= simple_format(@question.description) %></h2>
</div>
<div class="well col-xs-8 col-xs-offset-2">
  <table class="table table-bordered table-striped table-hover table-condensed">
    <tr>
      <td class="success text-center">Question ID</td>
      <td class="active data"> <%= @question.id %> </td>
    </tr>
    <tr>
      <td class="success text-center">Answer</td>
      <td class="active data"> <%= simple_format(@question.answer) %> </td>
    </tr>
    <tr>
      <td class="success text-center">Choice 1</td>
      <td class="active data"> <%= simple_format(@question.one) %> </td>
    </tr>
    <tr>
      <td class="success text-center">Choice 2</td>
      <td class="active data"> <%= simple_format(@question.two) %> </td>
    </tr>
    <tr>
      <td class="success text-center">Choice 3</td>
      <td class="active data"> <%= simple_format(@question.three) %> </td>
    </tr>
  </table>
</div>